// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.32.1
// source: attestation.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Terminal state of a child workflow at the moment of attestation.
type TerminalStatus int32

const (
	TerminalStatus_TERMINAL_STATUS_UNSPECIFIED TerminalStatus = 0
	TerminalStatus_TERMINAL_STATUS_COMPLETED   TerminalStatus = 1
	TerminalStatus_TERMINAL_STATUS_FAILED      TerminalStatus = 2
)

// Enum value maps for TerminalStatus.
var (
	TerminalStatus_name = map[int32]string{
		0: "TERMINAL_STATUS_UNSPECIFIED",
		1: "TERMINAL_STATUS_COMPLETED",
		2: "TERMINAL_STATUS_FAILED",
	}
	TerminalStatus_value = map[string]int32{
		"TERMINAL_STATUS_UNSPECIFIED": 0,
		"TERMINAL_STATUS_COMPLETED":   1,
		"TERMINAL_STATUS_FAILED":      2,
	}
)

func (x TerminalStatus) Enum() *TerminalStatus {
	p := new(TerminalStatus)
	*p = x
	return p
}

func (x TerminalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_attestation_proto_enumTypes[0].Descriptor()
}

func (TerminalStatus) Type() protoreflect.EnumType {
	return &file_attestation_proto_enumTypes[0]
}

func (x TerminalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminalStatus.Descriptor instead.
func (TerminalStatus) EnumDescriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{0}
}

// Terminal state of an activity task at the moment of attestation.
// Activities have no "terminate" operation, so the space is smaller than
// TerminalStatus.
type ActivityTerminalStatus int32

const (
	ActivityTerminalStatus_ACTIVITY_TERMINAL_STATUS_UNSPECIFIED ActivityTerminalStatus = 0
	ActivityTerminalStatus_ACTIVITY_TERMINAL_STATUS_COMPLETED   ActivityTerminalStatus = 1
	ActivityTerminalStatus_ACTIVITY_TERMINAL_STATUS_FAILED      ActivityTerminalStatus = 2
)

// Enum value maps for ActivityTerminalStatus.
var (
	ActivityTerminalStatus_name = map[int32]string{
		0: "ACTIVITY_TERMINAL_STATUS_UNSPECIFIED",
		1: "ACTIVITY_TERMINAL_STATUS_COMPLETED",
		2: "ACTIVITY_TERMINAL_STATUS_FAILED",
	}
	ActivityTerminalStatus_value = map[string]int32{
		"ACTIVITY_TERMINAL_STATUS_UNSPECIFIED": 0,
		"ACTIVITY_TERMINAL_STATUS_COMPLETED":   1,
		"ACTIVITY_TERMINAL_STATUS_FAILED":      2,
	}
)

func (x ActivityTerminalStatus) Enum() *ActivityTerminalStatus {
	p := new(ActivityTerminalStatus)
	*p = x
	return p
}

func (x ActivityTerminalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityTerminalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_attestation_proto_enumTypes[1].Descriptor()
}

func (ActivityTerminalStatus) Type() protoreflect.EnumType {
	return &file_attestation_proto_enumTypes[1]
}

func (x ActivityTerminalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityTerminalStatus.Descriptor instead.
func (ActivityTerminalStatus) EnumDescriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{1}
}

// Inner signed payload for a child workflow completion attestation. The
// canonical marshal of this message is what the signer signs over and
// what receivers verify against- never re-marshaled after production.
type ChildCompletionAttestationPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Parent workflow instance ID. Binds the attestation to a single parent
	// run, preventing replay by other instances of the same parent workflow
	// that share a signing key.
	ParentInstanceId string `protobuf:"bytes,1,opt,name=parentInstanceId,proto3" json:"parentInstanceId,omitempty"`
	// taskScheduledId from the parent's ChildWorkflowInstanceCreatedEvent.
	// Unique within the parent instance; distinguishes multiple invocations
	// of the same child workflow.
	ParentTaskScheduledId int32 `protobuf:"varint,2,opt,name=parentTaskScheduledId,proto3" json:"parentTaskScheduledId,omitempty"`
	// sha256 commitment to this invocation's input and output. The bytes
	// fed into the digest are produced by the canonical byte serialization
	// spec at the top of this file — not by any protobuf marshaler — so
	// the digest is stable across proto versions, implementations, and
	// languages. Use terminalStatus to select the output serialization rule
	// (COMPLETED or FAILED).
	IoDigest []byte `protobuf:"bytes,3,opt,name=ioDigest,proto3" json:"ioDigest,omitempty"`
	// sha256 of the DER-encoded X.509 certificate chain bytes of the
	// signer (leaf first, intermediates concatenated- same byte format
	// as the `certificate` field of SigningCertificate). Computed directly
	// over the DER bytes rather than any protobuf envelope, so the digest
	// is stable across protobuf version changes. The certificate itself
	// is carried as a companion field on the enclosing event on first
	// delivery and stored once in the receiver's external certificate
	// table (ext-sigcert-NNNNNN), looked up by this digest.
	SignerCertDigest []byte `protobuf:"bytes,4,opt,name=signerCertDigest,proto3" json:"signerCertDigest,omitempty"`
	// Terminal state of the child workflow at the moment of attestation.
	// Signed so that a verifier reading the attestation from propagated
	// history can tell whether the child succeeded without relying on the
	// enclosing event type (Completed vs Failed), which may not be
	// visible or trustworthy when the attestation is inspected in
	// isolation.
	TerminalStatus TerminalStatus `protobuf:"varint,5,opt,name=terminalStatus,proto3,enum=TerminalStatus" json:"terminalStatus,omitempty"`
	// Version of the canonical byte serialization spec used to compute
	// ioDigest. See the "Versioning" section of the spec block at the top
	// of this file. Verifiers that don't recognize the value reject the
	// attestation rather than risk a silent digest mismatch. Current
	// value: 1.
	CanonicalSpecVersion uint32 `protobuf:"varint,6,opt,name=canonicalSpecVersion,proto3" json:"canonicalSpecVersion,omitempty"`
}

func (x *ChildCompletionAttestationPayload) Reset() {
	*x = ChildCompletionAttestationPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attestation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChildCompletionAttestationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildCompletionAttestationPayload) ProtoMessage() {}

func (x *ChildCompletionAttestationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildCompletionAttestationPayload.ProtoReflect.Descriptor instead.
func (*ChildCompletionAttestationPayload) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *ChildCompletionAttestationPayload) GetParentInstanceId() string {
	if x != nil {
		return x.ParentInstanceId
	}
	return ""
}

func (x *ChildCompletionAttestationPayload) GetParentTaskScheduledId() int32 {
	if x != nil {
		return x.ParentTaskScheduledId
	}
	return 0
}

func (x *ChildCompletionAttestationPayload) GetIoDigest() []byte {
	if x != nil {
		return x.IoDigest
	}
	return nil
}

func (x *ChildCompletionAttestationPayload) GetSignerCertDigest() []byte {
	if x != nil {
		return x.SignerCertDigest
	}
	return nil
}

func (x *ChildCompletionAttestationPayload) GetTerminalStatus() TerminalStatus {
	if x != nil {
		return x.TerminalStatus
	}
	return TerminalStatus_TERMINAL_STATUS_UNSPECIFIED
}

func (x *ChildCompletionAttestationPayload) GetCanonicalSpecVersion() uint32 {
	if x != nil {
		return x.CanonicalSpecVersion
	}
	return 0
}

// Signed wrapper around ChildCompletionAttestationPayload.
type ChildCompletionAttestation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Canonical marshal of ChildCompletionAttestationPayload produced once
	// by the signer. Opaque bytes thereafter- receivers, storage, and
	// verifiers never re-marshal.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Cryptographic signature over sha256(payload) using the private key
	// corresponding to the certificate whose digest is in the payload's
	// signerCertDigest field. Signature format follows the same rules as
	// HistorySignature.signature.
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *ChildCompletionAttestation) Reset() {
	*x = ChildCompletionAttestation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attestation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChildCompletionAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildCompletionAttestation) ProtoMessage() {}

func (x *ChildCompletionAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildCompletionAttestation.ProtoReflect.Descriptor instead.
func (*ChildCompletionAttestation) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{1}
}

func (x *ChildCompletionAttestation) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChildCompletionAttestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Inner signed payload for an activity completion attestation. Activities
// have no signed history chain of their own (unlike child workflows), so
// there is no finalSignatureDigest field. Activity identity is the hosting
// app's SPIFFE identity- a compromised app can attest only to activities
// it hosts, not to activities hosted on other apps.
type ActivityCompletionAttestationPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Parent workflow instance ID that scheduled the activity.
	ParentInstanceId string `protobuf:"bytes,1,opt,name=parentInstanceId,proto3" json:"parentInstanceId,omitempty"`
	// taskScheduledId from the parent's TaskScheduledEvent. Unique within
	// the parent instance.
	ParentTaskScheduledId int32 `protobuf:"varint,2,opt,name=parentTaskScheduledId,proto3" json:"parentTaskScheduledId,omitempty"`
	// Activity name from the parent's TaskScheduledEvent. Explicit because
	// no separate creation event binds it in the parent's history the way
	// ChildWorkflowInstanceCreatedEvent does for child workflows.
	ActivityName string `protobuf:"bytes,3,opt,name=activityName,proto3" json:"activityName,omitempty"`
	// sha256 commitment to this invocation's input and output. See the
	// canonical byte serialization spec at the top of this file. Use
	// terminalStatus (ACTIVITY_TERMINAL_STATUS_COMPLETED or _FAILED) to
	// select the output serialization rule.
	IoDigest []byte `protobuf:"bytes,4,opt,name=ioDigest,proto3" json:"ioDigest,omitempty"`
	// sha256 of the DER-encoded X.509 certificate chain bytes of the
	// activity executor's signer. Same semantics and storage behavior as
	// ChildCompletionAttestationPayload.signerCertDigest.
	SignerCertDigest []byte `protobuf:"bytes,5,opt,name=signerCertDigest,proto3" json:"signerCertDigest,omitempty"`
	// Terminal state of the activity at the moment of attestation.
	TerminalStatus ActivityTerminalStatus `protobuf:"varint,6,opt,name=terminalStatus,proto3,enum=ActivityTerminalStatus" json:"terminalStatus,omitempty"`
	// Version of the canonical byte serialization spec used to compute
	// ioDigest. See the "Versioning" section of the spec block at the top
	// of this file. Verifiers that don't recognize the value reject the
	// attestation rather than risk a silent digest mismatch. Current
	// value: 1.
	CanonicalSpecVersion uint32 `protobuf:"varint,7,opt,name=canonicalSpecVersion,proto3" json:"canonicalSpecVersion,omitempty"`
}

func (x *ActivityCompletionAttestationPayload) Reset() {
	*x = ActivityCompletionAttestationPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attestation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityCompletionAttestationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityCompletionAttestationPayload) ProtoMessage() {}

func (x *ActivityCompletionAttestationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityCompletionAttestationPayload.ProtoReflect.Descriptor instead.
func (*ActivityCompletionAttestationPayload) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityCompletionAttestationPayload) GetParentInstanceId() string {
	if x != nil {
		return x.ParentInstanceId
	}
	return ""
}

func (x *ActivityCompletionAttestationPayload) GetParentTaskScheduledId() int32 {
	if x != nil {
		return x.ParentTaskScheduledId
	}
	return 0
}

func (x *ActivityCompletionAttestationPayload) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *ActivityCompletionAttestationPayload) GetIoDigest() []byte {
	if x != nil {
		return x.IoDigest
	}
	return nil
}

func (x *ActivityCompletionAttestationPayload) GetSignerCertDigest() []byte {
	if x != nil {
		return x.SignerCertDigest
	}
	return nil
}

func (x *ActivityCompletionAttestationPayload) GetTerminalStatus() ActivityTerminalStatus {
	if x != nil {
		return x.TerminalStatus
	}
	return ActivityTerminalStatus_ACTIVITY_TERMINAL_STATUS_UNSPECIFIED
}

func (x *ActivityCompletionAttestationPayload) GetCanonicalSpecVersion() uint32 {
	if x != nil {
		return x.CanonicalSpecVersion
	}
	return 0
}

// Signed wrapper around ActivityCompletionAttestationPayload.
type ActivityCompletionAttestation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Canonical marshal of ActivityCompletionAttestationPayload produced
	// once by the signer. Opaque bytes thereafter.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Cryptographic signature over sha256(payload).
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *ActivityCompletionAttestation) Reset() {
	*x = ActivityCompletionAttestation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attestation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityCompletionAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityCompletionAttestation) ProtoMessage() {}

func (x *ActivityCompletionAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityCompletionAttestation.ProtoReflect.Descriptor instead.
func (*ActivityCompletionAttestation) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityCompletionAttestation) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ActivityCompletionAttestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// A foreign signer's X.509 certificate- one belonging to another workflow
// instance or activity executor whose attestations this workflow has
// received. Stored once per unique digest and referenced by digest from
// any attestation embedded in history. Stored as individual actor state
// keys: ext-sigcert-000000, ext-sigcert-000001, etc.
//
// Lifecycle mirrors SigningCertificate (monotonically appended within a
// run, cleared on ContinueAsNew and instance purge, tracked by
// BackendWorkflowStateMetadata.externalSigningCertificateLength). Dedup
// within a run is performed by in-memory digest→index lookup built at
// load time.
type ExternalSigningCertificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sha256 of the DER-encoded X.509 certificate chain bytes (the value
	// in `certificate` below). Also the primary lookup key used by
	// attestations' signerCertDigest fields. Stored explicitly so
	// load-time index construction and post-load integrity checks do not
	// have to re-hash every entry.
	Digest []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// Same byte format as SigningCertificate.certificate: DER-encoded
	// X.509 chain, leaf first, intermediates concatenated.
	Certificate []byte `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
}

func (x *ExternalSigningCertificate) Reset() {
	*x = ExternalSigningCertificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attestation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalSigningCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalSigningCertificate) ProtoMessage() {}

func (x *ExternalSigningCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalSigningCertificate.ProtoReflect.Descriptor instead.
func (*ExternalSigningCertificate) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{4}
}

func (x *ExternalSigningCertificate) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *ExternalSigningCertificate) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

var File_attestation_proto protoreflect.FileDescriptor

var file_attestation_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xba, 0x02, 0x0a, 0x21, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x15, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x6f, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69,
	0x6f, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x43, 0x65, 0x72, 0x74, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x10, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x43, 0x65, 0x72, 0x74, 0x44, 0x69, 0x67,
	0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x54, 0x65,
	0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x74, 0x65,
	0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x32, 0x0a, 0x14,
	0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x14, 0x63, 0x61, 0x6e, 0x6f,
	0x6e, 0x69, 0x63, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x54, 0x0a, 0x1a, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xe9, 0x02, 0x0a, 0x24, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74,
	0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x2a, 0x0a, 0x10, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x15, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x64, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6f, 0x44, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6f, 0x44, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x43, 0x65, 0x72, 0x74, 0x44,
	0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x43, 0x65, 0x72, 0x74, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a,
	0x0e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e,
	0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x32,
	0x0a, 0x14, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x14, 0x63, 0x61,
	0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x57, 0x0a, 0x1d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x56, 0x0a, 0x1a, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x2a, 0x6c, 0x0a, 0x0e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x1b, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41,
	0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e,
	0x41, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45,
	0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41,
	0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10,
	0x02, 0x2a, 0x8f, 0x01, 0x0a, 0x16, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x65,
	0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x24,
	0x41, 0x43, 0x54, 0x49, 0x56, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41,
	0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x26, 0x0a, 0x22, 0x41, 0x43, 0x54, 0x49, 0x56, 0x49,
	0x54, 0x59, 0x5f, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x23,
	0x0a, 0x1f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x45, 0x52, 0x4d, 0x49,
	0x4e, 0x41, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45,
	0x44, 0x10, 0x02, 0x42, 0x56, 0x0a, 0x2b, 0x69, 0x6f, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x64,
	0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x5a, 0x0b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0xaa,
	0x02, 0x19, 0x44, 0x61, 0x70, 0x72, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_attestation_proto_rawDescOnce sync.Once
	file_attestation_proto_rawDescData = file_attestation_proto_rawDesc
)

func file_attestation_proto_rawDescGZIP() []byte {
	file_attestation_proto_rawDescOnce.Do(func() {
		file_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(file_attestation_proto_rawDescData)
	})
	return file_attestation_proto_rawDescData
}

var file_attestation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_attestation_proto_goTypes = []interface{}{
	(TerminalStatus)(0),                          // 0: TerminalStatus
	(ActivityTerminalStatus)(0),                  // 1: ActivityTerminalStatus
	(*ChildCompletionAttestationPayload)(nil),    // 2: ChildCompletionAttestationPayload
	(*ChildCompletionAttestation)(nil),           // 3: ChildCompletionAttestation
	(*ActivityCompletionAttestationPayload)(nil), // 4: ActivityCompletionAttestationPayload
	(*ActivityCompletionAttestation)(nil),        // 5: ActivityCompletionAttestation
	(*ExternalSigningCertificate)(nil),           // 6: ExternalSigningCertificate
}
var file_attestation_proto_depIdxs = []int32{
	0, // 0: ChildCompletionAttestationPayload.terminalStatus:type_name -> TerminalStatus
	1, // 1: ActivityCompletionAttestationPayload.terminalStatus:type_name -> ActivityTerminalStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_attestation_proto_init() }
func file_attestation_proto_init() {
	if File_attestation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_attestation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChildCompletionAttestationPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attestation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChildCompletionAttestation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attestation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityCompletionAttestationPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attestation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityCompletionAttestation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attestation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalSigningCertificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_attestation_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attestation_proto_goTypes,
		DependencyIndexes: file_attestation_proto_depIdxs,
		EnumInfos:         file_attestation_proto_enumTypes,
		MessageInfos:      file_attestation_proto_msgTypes,
	}.Build()
	File_attestation_proto = out.File
	file_attestation_proto_rawDesc = nil
	file_attestation_proto_goTypes = nil
	file_attestation_proto_depIdxs = nil
}
