// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v7.34.1
// source: backend_service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request payload for adding new workflow events.
type AddEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the workflow to send an event to.
	Instance *WorkflowInstance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// The event to send to the workflow.
	Event *HistoryEvent `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *AddEventRequest) Reset() {
	*x = AddEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventRequest) ProtoMessage() {}

func (x *AddEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventRequest.ProtoReflect.Descriptor instead.
func (*AddEventRequest) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddEventRequest) GetInstance() *WorkflowInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *AddEventRequest) GetEvent() *HistoryEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// Response payload for adding new workflow events.
type AddEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddEventResponse) Reset() {
	*x = AddEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventResponse) ProtoMessage() {}

func (x *AddEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventResponse.ProtoReflect.Descriptor instead.
func (*AddEventResponse) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{1}
}

// Request payload for completing an activity work item.
type CompleteActivityWorkItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The completion token that was provided when the work item was fetched.
	CompletionToken string `protobuf:"bytes,1,opt,name=completionToken,proto3" json:"completionToken,omitempty"`
	// The response event that will be sent to the workflow.
	// This must be either a TaskCompleted event or a TaskFailed event.
	ResponseEvent *HistoryEvent `protobuf:"bytes,2,opt,name=responseEvent,proto3" json:"responseEvent,omitempty"`
}

func (x *CompleteActivityWorkItemRequest) Reset() {
	*x = CompleteActivityWorkItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteActivityWorkItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteActivityWorkItemRequest) ProtoMessage() {}

func (x *CompleteActivityWorkItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteActivityWorkItemRequest.ProtoReflect.Descriptor instead.
func (*CompleteActivityWorkItemRequest) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteActivityWorkItemRequest) GetCompletionToken() string {
	if x != nil {
		return x.CompletionToken
	}
	return ""
}

func (x *CompleteActivityWorkItemRequest) GetResponseEvent() *HistoryEvent {
	if x != nil {
		return x.ResponseEvent
	}
	return nil
}

// Response payload for completing an activity work item.
type CompleteActivityWorkItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompleteActivityWorkItemResponse) Reset() {
	*x = CompleteActivityWorkItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteActivityWorkItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteActivityWorkItemResponse) ProtoMessage() {}

func (x *CompleteActivityWorkItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteActivityWorkItemResponse.ProtoReflect.Descriptor instead.
func (*CompleteActivityWorkItemResponse) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{3}
}

// Request payload for completing a workflow work item.
type CompleteWorkflowWorkItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The completion token that was provided when the work item was fetched.
	CompletionToken string                  `protobuf:"bytes,1,opt,name=completionToken,proto3" json:"completionToken,omitempty"`
	Instance        *WorkflowInstance       `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	RuntimeStatus   OrchestrationStatus     `protobuf:"varint,3,opt,name=runtimeStatus,proto3,enum=OrchestrationStatus" json:"runtimeStatus,omitempty"`
	CustomStatus    *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=customStatus,proto3" json:"customStatus,omitempty"`
	NewHistory      []*HistoryEvent         `protobuf:"bytes,5,rep,name=newHistory,proto3" json:"newHistory,omitempty"`
	NewTasks        []*HistoryEvent         `protobuf:"bytes,6,rep,name=newTasks,proto3" json:"newTasks,omitempty"`
	NewTimers       []*HistoryEvent         `protobuf:"bytes,7,rep,name=newTimers,proto3" json:"newTimers,omitempty"`
	NewMessages     []*WorkflowMessage      `protobuf:"bytes,8,rep,name=newMessages,proto3" json:"newMessages,omitempty"`
	// The number of work item events that were processed by the workflow.
	// This field is optional. If not set, the service should assume that the workflow processed all events.
	NumEventsProcessed *wrapperspb.Int32Value `protobuf:"bytes,9,opt,name=numEventsProcessed,proto3" json:"numEventsProcessed,omitempty"`
}

func (x *CompleteWorkflowWorkItemRequest) Reset() {
	*x = CompleteWorkflowWorkItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteWorkflowWorkItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteWorkflowWorkItemRequest) ProtoMessage() {}

func (x *CompleteWorkflowWorkItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteWorkflowWorkItemRequest.ProtoReflect.Descriptor instead.
func (*CompleteWorkflowWorkItemRequest) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteWorkflowWorkItemRequest) GetCompletionToken() string {
	if x != nil {
		return x.CompletionToken
	}
	return ""
}

func (x *CompleteWorkflowWorkItemRequest) GetInstance() *WorkflowInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *CompleteWorkflowWorkItemRequest) GetRuntimeStatus() OrchestrationStatus {
	if x != nil {
		return x.RuntimeStatus
	}
	return OrchestrationStatus_ORCHESTRATION_STATUS_RUNNING
}

func (x *CompleteWorkflowWorkItemRequest) GetCustomStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.CustomStatus
	}
	return nil
}

func (x *CompleteWorkflowWorkItemRequest) GetNewHistory() []*HistoryEvent {
	if x != nil {
		return x.NewHistory
	}
	return nil
}

func (x *CompleteWorkflowWorkItemRequest) GetNewTasks() []*HistoryEvent {
	if x != nil {
		return x.NewTasks
	}
	return nil
}

func (x *CompleteWorkflowWorkItemRequest) GetNewTimers() []*HistoryEvent {
	if x != nil {
		return x.NewTimers
	}
	return nil
}

func (x *CompleteWorkflowWorkItemRequest) GetNewMessages() []*WorkflowMessage {
	if x != nil {
		return x.NewMessages
	}
	return nil
}

func (x *CompleteWorkflowWorkItemRequest) GetNumEventsProcessed() *wrapperspb.Int32Value {
	if x != nil {
		return x.NumEventsProcessed
	}
	return nil
}

// Response payload for completing a workflow work item.
type CompleteWorkflowWorkItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompleteWorkflowWorkItemResponse) Reset() {
	*x = CompleteWorkflowWorkItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteWorkflowWorkItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteWorkflowWorkItemResponse) ProtoMessage() {}

func (x *CompleteWorkflowWorkItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteWorkflowWorkItemResponse.ProtoReflect.Descriptor instead.
func (*CompleteWorkflowWorkItemResponse) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{5}
}

// A message to be delivered to a workflow by the backend.
type WorkflowMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the workflow instance to receive the message.
	Instance *WorkflowInstance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// The event payload to be received by the target workflow.
	Event *HistoryEvent `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *WorkflowMessage) Reset() {
	*x = WorkflowMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowMessage) ProtoMessage() {}

func (x *WorkflowMessage) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowMessage.ProtoReflect.Descriptor instead.
func (*WorkflowMessage) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowMessage) GetInstance() *WorkflowInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *WorkflowMessage) GetEvent() *HistoryEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type BackendWorkflowState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inbox        []*HistoryEvent         `protobuf:"bytes,1,rep,name=inbox,proto3" json:"inbox,omitempty"`
	History      []*HistoryEvent         `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	CustomStatus *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=customStatus,proto3" json:"customStatus,omitempty"`
	Generation   uint64                  `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
}

func (x *BackendWorkflowState) Reset() {
	*x = BackendWorkflowState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendWorkflowState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendWorkflowState) ProtoMessage() {}

func (x *BackendWorkflowState) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendWorkflowState.ProtoReflect.Descriptor instead.
func (*BackendWorkflowState) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{7}
}

func (x *BackendWorkflowState) GetInbox() []*HistoryEvent {
	if x != nil {
		return x.Inbox
	}
	return nil
}

func (x *BackendWorkflowState) GetHistory() []*HistoryEvent {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *BackendWorkflowState) GetCustomStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.CustomStatus
	}
	return nil
}

func (x *BackendWorkflowState) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type CreateWorkflowInstanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartEvent *HistoryEvent `protobuf:"bytes,1,opt,name=startEvent,proto3" json:"startEvent,omitempty"`
}

func (x *CreateWorkflowInstanceRequest) Reset() {
	*x = CreateWorkflowInstanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkflowInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowInstanceRequest) ProtoMessage() {}

func (x *CreateWorkflowInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowInstanceRequest) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateWorkflowInstanceRequest) GetStartEvent() *HistoryEvent {
	if x != nil {
		return x.StartEvent
	}
	return nil
}

type WorkflowMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId       string                  `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Name             string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RuntimeStatus    OrchestrationStatus     `protobuf:"varint,3,opt,name=runtimeStatus,proto3,enum=OrchestrationStatus" json:"runtimeStatus,omitempty"`
	CreatedAt        *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	LastUpdatedAt    *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=lastUpdatedAt,proto3" json:"lastUpdatedAt,omitempty"`
	Input            *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	Output           *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=output,proto3" json:"output,omitempty"`
	CustomStatus     *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=customStatus,proto3" json:"customStatus,omitempty"`
	FailureDetails   *TaskFailureDetails     `protobuf:"bytes,9,opt,name=failureDetails,proto3" json:"failureDetails,omitempty"`
	CompletedAt      *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=completedAt,proto3" json:"completedAt,omitempty"`
	ParentInstanceId string                  `protobuf:"bytes,11,opt,name=parentInstanceId,proto3" json:"parentInstanceId,omitempty"`
}

func (x *WorkflowMetadata) Reset() {
	*x = WorkflowMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowMetadata) ProtoMessage() {}

func (x *WorkflowMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowMetadata.ProtoReflect.Descriptor instead.
func (*WorkflowMetadata) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{9}
}

func (x *WorkflowMetadata) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *WorkflowMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowMetadata) GetRuntimeStatus() OrchestrationStatus {
	if x != nil {
		return x.RuntimeStatus
	}
	return OrchestrationStatus_ORCHESTRATION_STATUS_RUNNING
}

func (x *WorkflowMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkflowMetadata) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

func (x *WorkflowMetadata) GetInput() *wrapperspb.StringValue {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *WorkflowMetadata) GetOutput() *wrapperspb.StringValue {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *WorkflowMetadata) GetCustomStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.CustomStatus
	}
	return nil
}

func (x *WorkflowMetadata) GetFailureDetails() *TaskFailureDetails {
	if x != nil {
		return x.FailureDetails
	}
	return nil
}

func (x *WorkflowMetadata) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *WorkflowMetadata) GetParentInstanceId() string {
	if x != nil {
		return x.ParentInstanceId
	}
	return ""
}

type BackendWorkflowStateMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InboxLength   uint64 `protobuf:"varint,1,opt,name=inboxLength,proto3" json:"inboxLength,omitempty"`
	HistoryLength uint64 `protobuf:"varint,2,opt,name=historyLength,proto3" json:"historyLength,omitempty"`
	Generation    uint64 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	// Number of HistorySignature entries stored (signature-NNNNNN keys).
	SignatureLength uint64 `protobuf:"varint,4,opt,name=signatureLength,proto3" json:"signatureLength,omitempty"`
	// Number of SigningCertificate entries stored (sigcert-NNNNNN keys).
	SigningCertificateLength uint64 `protobuf:"varint,5,opt,name=signingCertificateLength,proto3" json:"signingCertificateLength,omitempty"`
}

func (x *BackendWorkflowStateMetadata) Reset() {
	*x = BackendWorkflowStateMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendWorkflowStateMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendWorkflowStateMetadata) ProtoMessage() {}

func (x *BackendWorkflowStateMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendWorkflowStateMetadata.ProtoReflect.Descriptor instead.
func (*BackendWorkflowStateMetadata) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{10}
}

func (x *BackendWorkflowStateMetadata) GetInboxLength() uint64 {
	if x != nil {
		return x.InboxLength
	}
	return 0
}

func (x *BackendWorkflowStateMetadata) GetHistoryLength() uint64 {
	if x != nil {
		return x.HistoryLength
	}
	return 0
}

func (x *BackendWorkflowStateMetadata) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *BackendWorkflowStateMetadata) GetSignatureLength() uint64 {
	if x != nil {
		return x.SignatureLength
	}
	return 0
}

func (x *BackendWorkflowStateMetadata) GetSigningCertificateLength() uint64 {
	if x != nil {
		return x.SigningCertificateLength
	}
	return 0
}

// A signing identity's X.509 certificate, stored once and referenced by index
// from HistorySignature entries. This avoids duplicating the certificate
// across every signature from the same identity. Stored as individual actor
// state keys: sigcert-000000, sigcert-000001, etc.
type SigningCertificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// X.509 certificate chain of the signing identity. Certificates are
	// DER-encoded and concatenated directly in order: leaf first, followed by
	// intermediates. Each certificate is a self-delimiting ASN.1 SEQUENCE,
	// so the chain can be parsed by reading consecutive DER structures.
	Certificate []byte `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
}

func (x *SigningCertificate) Reset() {
	*x = SigningCertificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningCertificate) ProtoMessage() {}

func (x *SigningCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningCertificate.ProtoReflect.Descriptor instead.
func (*SigningCertificate) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{11}
}

func (x *SigningCertificate) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

// Signing metadata for a contiguous range of history events.
// This is metadata-only — it does NOT contain the events themselves.
// Events are stored once in history-NNNNNN keys; this message references them
// by index range and stores only the signing artifacts.
// Stored as individual actor state keys: signature-000000, signature-000001,
// etc.
type HistorySignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Index of the first event covered by this signature (inclusive).
	StartEventIndex uint64 `protobuf:"varint,1,opt,name=startEventIndex,proto3" json:"startEventIndex,omitempty"`
	// Number of events covered by this signature.
	EventCount uint64 `protobuf:"varint,2,opt,name=eventCount,proto3" json:"eventCount,omitempty"`
	// SHA-256 digest of the previous HistorySignature message (the entire
	// deterministically serialized protobuf message). Absent for the first
	// signature in the chain (no predecessor). When computing the signature
	// input for the root case, this value is treated as empty (zero-length).
	PreviousSignatureDigest []byte `protobuf:"bytes,3,opt,name=previousSignatureDigest,proto3,oneof" json:"previousSignatureDigest,omitempty"`
	// SHA-256 digest over the concatenation of the raw serialized bytes of each
	// history event in this range, in order. The bytes are the exact values
	// persisted to the state store (one per history-NNNNNN key).
	EventsDigest []byte `protobuf:"bytes,4,opt,name=eventsDigest,proto3" json:"eventsDigest,omitempty"`
	// Index into the SigningCertificate table (sigcert-NNNNNN keys).
	// Multiple signatures from the same identity share the same index.
	// A new entry is appended only when the certificate rotates.
	CertificateIndex uint64 `protobuf:"varint,5,opt,name=certificateIndex,proto3" json:"certificateIndex,omitempty"`
	// Cryptographic signature over
	// SHA-256(previousSignatureDigest || eventsDigest)
	// using the private key corresponding to the referenced certificate.
	// The algorithm is determined by the certificate's key type:
	//
	//	Ed25519: raw Ed25519 signature over the input bytes
	//	ECDSA:   fixed-size r||s over SHA-256(input), each component
	//	         zero-padded to the curve byte length
	//	RSA:     PKCS#1 v1.5 with SHA-256
	Signature []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *HistorySignature) Reset() {
	*x = HistorySignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistorySignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistorySignature) ProtoMessage() {}

func (x *HistorySignature) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistorySignature.ProtoReflect.Descriptor instead.
func (*HistorySignature) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{12}
}

func (x *HistorySignature) GetStartEventIndex() uint64 {
	if x != nil {
		return x.StartEventIndex
	}
	return 0
}

func (x *HistorySignature) GetEventCount() uint64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *HistorySignature) GetPreviousSignatureDigest() []byte {
	if x != nil {
		return x.PreviousSignatureDigest
	}
	return nil
}

func (x *HistorySignature) GetEventsDigest() []byte {
	if x != nil {
		return x.EventsDigest
	}
	return nil
}

func (x *HistorySignature) GetCertificateIndex() uint64 {
	if x != nil {
		return x.CertificateIndex
	}
	return 0
}

func (x *HistorySignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type DurableTimer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerEvent *HistoryEvent `protobuf:"bytes,1,opt,name=timerEvent,proto3" json:"timerEvent,omitempty"`
	Generation uint64        `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
}

func (x *DurableTimer) Reset() {
	*x = DurableTimer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DurableTimer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurableTimer) ProtoMessage() {}

func (x *DurableTimer) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurableTimer.ProtoReflect.Descriptor instead.
func (*DurableTimer) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{13}
}

func (x *DurableTimer) GetTimerEvent() *HistoryEvent {
	if x != nil {
		return x.TimerEvent
	}
	return nil
}

func (x *DurableTimer) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

var File_backend_service_proto protoreflect.FileDescriptor

var file_backend_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x64, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65,
	0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x13, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x65, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c,
	0x6f, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x64, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x80, 0x01,
	0x0a, 0x1f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x33, 0x0a, 0x0d, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0x22, 0x0a, 0x20, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x9e, 0x04, 0x0a, 0x1f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x2d, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x65,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x40, 0x0a,
	0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x2d, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x29,
	0x0a, 0x08, 0x6e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x08, 0x6e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x6e, 0x65, 0x77,
	0x54, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x6e, 0x65, 0x77,
	0x54, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x12, 0x50, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x64, 0x75,
	0x72, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x6e, 0x65, 0x77,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x12, 0x6e, 0x75, 0x6d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x12, 0x6e, 0x75, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x22, 0x22, 0x0a, 0x20, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x65, 0x0a, 0x0f, 0x57, 0x6f, 0x72,
	0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x08,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0xc6, 0x01, 0x0a, 0x14, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x57, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x6e, 0x62,
	0x6f, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x12, 0x27,
	0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x07,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x40, 0x0a, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x1d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x52,
	0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0xd1, 0x04, 0x0a, 0x10, 0x57, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x3a, 0x0a, 0x0d, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x40, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x32, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x34, 0x0a, 0x06,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x40, 0x0a, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x3b, 0x0a, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x3c, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x2a, 0x0a, 0x10, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0xec, 0x01, 0x0a, 0x1c,
	0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b,
	0x69, 0x6e, 0x62, 0x6f, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x24,
	0x0a, 0x0d, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x3a,
	0x0a, 0x18, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x18, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x36, 0x0a, 0x12, 0x53, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x22, 0xa5, 0x02, 0x0a, 0x10, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x3d, 0x0a, 0x17, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x17, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x22, 0x0a, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x44, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10,
	0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x1a,
	0x0a, 0x18, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x0c, 0x44, 0x75,
	0x72, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x0a, 0x74, 0x69,
	0x6d, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x74,
	0x69, 0x6d, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x56, 0x0a, 0x2b, 0x69, 0x6f, 0x2e,
	0x64, 0x61, 0x70, 0x72, 0x2e, 0x64, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x61, 0x73, 0x6b,
	0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5a, 0x0b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0xaa, 0x02, 0x19, 0x44, 0x61, 0x70, 0x72, 0x2e, 0x44, 0x75, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_service_proto_rawDescOnce sync.Once
	file_backend_service_proto_rawDescData = file_backend_service_proto_rawDesc
)

func file_backend_service_proto_rawDescGZIP() []byte {
	file_backend_service_proto_rawDescOnce.Do(func() {
		file_backend_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_service_proto_rawDescData)
	})
	return file_backend_service_proto_rawDescData
}

var file_backend_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_backend_service_proto_goTypes = []interface{}{
	(*AddEventRequest)(nil),                  // 0: durabletask.protos.backend.v1.AddEventRequest
	(*AddEventResponse)(nil),                 // 1: durabletask.protos.backend.v1.AddEventResponse
	(*CompleteActivityWorkItemRequest)(nil),  // 2: durabletask.protos.backend.v1.CompleteActivityWorkItemRequest
	(*CompleteActivityWorkItemResponse)(nil), // 3: durabletask.protos.backend.v1.CompleteActivityWorkItemResponse
	(*CompleteWorkflowWorkItemRequest)(nil),  // 4: durabletask.protos.backend.v1.CompleteWorkflowWorkItemRequest
	(*CompleteWorkflowWorkItemResponse)(nil), // 5: durabletask.protos.backend.v1.CompleteWorkflowWorkItemResponse
	(*WorkflowMessage)(nil),                  // 6: durabletask.protos.backend.v1.WorkflowMessage
	(*BackendWorkflowState)(nil),             // 7: durabletask.protos.backend.v1.BackendWorkflowState
	(*CreateWorkflowInstanceRequest)(nil),    // 8: durabletask.protos.backend.v1.CreateWorkflowInstanceRequest
	(*WorkflowMetadata)(nil),                 // 9: durabletask.protos.backend.v1.WorkflowMetadata
	(*BackendWorkflowStateMetadata)(nil),     // 10: durabletask.protos.backend.v1.BackendWorkflowStateMetadata
	(*SigningCertificate)(nil),               // 11: durabletask.protos.backend.v1.SigningCertificate
	(*HistorySignature)(nil),                 // 12: durabletask.protos.backend.v1.HistorySignature
	(*DurableTimer)(nil),                     // 13: durabletask.protos.backend.v1.DurableTimer
	(*WorkflowInstance)(nil),                 // 14: WorkflowInstance
	(*HistoryEvent)(nil),                     // 15: HistoryEvent
	(OrchestrationStatus)(0),                 // 16: OrchestrationStatus
	(*wrapperspb.StringValue)(nil),           // 17: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),            // 18: google.protobuf.Int32Value
	(*timestamppb.Timestamp)(nil),            // 19: google.protobuf.Timestamp
	(*TaskFailureDetails)(nil),               // 20: TaskFailureDetails
}
var file_backend_service_proto_depIdxs = []int32{
	14, // 0: durabletask.protos.backend.v1.AddEventRequest.instance:type_name -> WorkflowInstance
	15, // 1: durabletask.protos.backend.v1.AddEventRequest.event:type_name -> HistoryEvent
	15, // 2: durabletask.protos.backend.v1.CompleteActivityWorkItemRequest.responseEvent:type_name -> HistoryEvent
	14, // 3: durabletask.protos.backend.v1.CompleteWorkflowWorkItemRequest.instance:type_name -> WorkflowInstance
	16, // 4: durabletask.protos.backend.v1.CompleteWorkflowWorkItemRequest.runtimeStatus:type_name -> OrchestrationStatus
	17, // 5: durabletask.protos.backend.v1.CompleteWorkflowWorkItemRequest.customStatus:type_name -> google.protobuf.StringValue
	15, // 6: durabletask.protos.backend.v1.CompleteWorkflowWorkItemRequest.newHistory:type_name -> HistoryEvent
	15, // 7: durabletask.protos.backend.v1.CompleteWorkflowWorkItemRequest.newTasks:type_name -> HistoryEvent
	15, // 8: durabletask.protos.backend.v1.CompleteWorkflowWorkItemRequest.newTimers:type_name -> HistoryEvent
	6,  // 9: durabletask.protos.backend.v1.CompleteWorkflowWorkItemRequest.newMessages:type_name -> durabletask.protos.backend.v1.WorkflowMessage
	18, // 10: durabletask.protos.backend.v1.CompleteWorkflowWorkItemRequest.numEventsProcessed:type_name -> google.protobuf.Int32Value
	14, // 11: durabletask.protos.backend.v1.WorkflowMessage.instance:type_name -> WorkflowInstance
	15, // 12: durabletask.protos.backend.v1.WorkflowMessage.event:type_name -> HistoryEvent
	15, // 13: durabletask.protos.backend.v1.BackendWorkflowState.inbox:type_name -> HistoryEvent
	15, // 14: durabletask.protos.backend.v1.BackendWorkflowState.history:type_name -> HistoryEvent
	17, // 15: durabletask.protos.backend.v1.BackendWorkflowState.customStatus:type_name -> google.protobuf.StringValue
	15, // 16: durabletask.protos.backend.v1.CreateWorkflowInstanceRequest.startEvent:type_name -> HistoryEvent
	16, // 17: durabletask.protos.backend.v1.WorkflowMetadata.runtimeStatus:type_name -> OrchestrationStatus
	19, // 18: durabletask.protos.backend.v1.WorkflowMetadata.createdAt:type_name -> google.protobuf.Timestamp
	19, // 19: durabletask.protos.backend.v1.WorkflowMetadata.lastUpdatedAt:type_name -> google.protobuf.Timestamp
	17, // 20: durabletask.protos.backend.v1.WorkflowMetadata.input:type_name -> google.protobuf.StringValue
	17, // 21: durabletask.protos.backend.v1.WorkflowMetadata.output:type_name -> google.protobuf.StringValue
	17, // 22: durabletask.protos.backend.v1.WorkflowMetadata.customStatus:type_name -> google.protobuf.StringValue
	20, // 23: durabletask.protos.backend.v1.WorkflowMetadata.failureDetails:type_name -> TaskFailureDetails
	19, // 24: durabletask.protos.backend.v1.WorkflowMetadata.completedAt:type_name -> google.protobuf.Timestamp
	15, // 25: durabletask.protos.backend.v1.DurableTimer.timerEvent:type_name -> HistoryEvent
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_backend_service_proto_init() }
func file_backend_service_proto_init() {
	if File_backend_service_proto != nil {
		return
	}
	file_orchestration_proto_init()
	file_history_events_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_backend_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteActivityWorkItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteActivityWorkItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteWorkflowWorkItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteWorkflowWorkItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendWorkflowState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkflowInstanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendWorkflowStateMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningCertificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistorySignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DurableTimer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_backend_service_proto_msgTypes[12].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_service_proto_goTypes,
		DependencyIndexes: file_backend_service_proto_depIdxs,
		MessageInfos:      file_backend_service_proto_msgTypes,
	}.Build()
	File_backend_service_proto = out.File
	file_backend_service_proto_rawDesc = nil
	file_backend_service_proto_goTypes = nil
	file_backend_service_proto_depIdxs = nil
}
