//
//Copyright 2026 The Dapr Authors
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v7.34.1
// source: mcp.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InProcessWorkflow identifies a category of Dapr internal workflow.
// Workflow name format: dapr.internal.<workflow>.<resource>.<method>
//
// SDKs map enum values to string prefixes:
//
//	IN_PROCESS_WORKFLOW_MCP → "dapr.internal.mcp."
type InProcessWorkflow int32

const (
	// MCP: Model Context Protocol server orchestrations.
	// Prefix: "dapr.internal.mcp."
	InProcessWorkflow_IN_PROCESS_WORKFLOW_MCP InProcessWorkflow = 0
)

// Enum value maps for InProcessWorkflow.
var (
	InProcessWorkflow_name = map[int32]string{
		0: "IN_PROCESS_WORKFLOW_MCP",
	}
	InProcessWorkflow_value = map[string]int32{
		"IN_PROCESS_WORKFLOW_MCP": 0,
	}
)

func (x InProcessWorkflow) Enum() *InProcessWorkflow {
	p := new(InProcessWorkflow)
	*p = x
	return p
}

func (x InProcessWorkflow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InProcessWorkflow) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_proto_enumTypes[0].Descriptor()
}

func (InProcessWorkflow) Type() protoreflect.EnumType {
	return &file_mcp_proto_enumTypes[0]
}

func (x InProcessWorkflow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InProcessWorkflow.Descriptor instead.
func (InProcessWorkflow) EnumDescriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{0}
}

// MCPMethod identifies an operation within the MCP internal workflow.
// SDKs map enum values to PascalCase method suffixes:
//
//	MCP_METHOD_LIST_TOOLS → ".ListTools"
//	MCP_METHOD_CALL_TOOL  → ".CallTool"
type MCPMethod int32

const (
	// Discovers available tools on an MCPServer.
	MCPMethod_MCP_METHOD_LIST_TOOLS MCPMethod = 0
	// Invokes a specific tool on an MCPServer.
	MCPMethod_MCP_METHOD_CALL_TOOL MCPMethod = 1
)

// Enum value maps for MCPMethod.
var (
	MCPMethod_name = map[int32]string{
		0: "MCP_METHOD_LIST_TOOLS",
		1: "MCP_METHOD_CALL_TOOL",
	}
	MCPMethod_value = map[string]int32{
		"MCP_METHOD_LIST_TOOLS": 0,
		"MCP_METHOD_CALL_TOOL":  1,
	}
)

func (x MCPMethod) Enum() *MCPMethod {
	p := new(MCPMethod)
	*p = x
	return p
}

func (x MCPMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_proto_enumTypes[1].Descriptor()
}

func (MCPMethod) Type() protoreflect.EnumType {
	return &file_mcp_proto_enumTypes[1]
}

func (x MCPMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPMethod.Descriptor instead.
func (MCPMethod) EnumDescriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{1}
}

var File_mcp_proto protoreflect.FileDescriptor

var file_mcp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x30, 0x0a, 0x11, 0x49,
	0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x12, 0x1b, 0x0a, 0x17, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x57,
	0x4f, 0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57, 0x5f, 0x4d, 0x43, 0x50, 0x10, 0x00, 0x2a, 0x40, 0x0a,
	0x09, 0x4d, 0x43, 0x50, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x43,
	0x50, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x54, 0x4f,
	0x4f, 0x4c, 0x53, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x43, 0x50, 0x5f, 0x4d, 0x45, 0x54,
	0x48, 0x4f, 0x44, 0x5f, 0x43, 0x41, 0x4c, 0x4c, 0x5f, 0x54, 0x4f, 0x4f, 0x4c, 0x10, 0x01, 0x42,
	0x56, 0x0a, 0x2b, 0x69, 0x6f, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x64, 0x75, 0x72, 0x61, 0x62,
	0x6c, 0x65, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5a, 0x0b,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0xaa, 0x02, 0x19, 0x44, 0x61,
	0x70, 0x72, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mcp_proto_rawDescOnce sync.Once
	file_mcp_proto_rawDescData = file_mcp_proto_rawDesc
)

func file_mcp_proto_rawDescGZIP() []byte {
	file_mcp_proto_rawDescOnce.Do(func() {
		file_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(file_mcp_proto_rawDescData)
	})
	return file_mcp_proto_rawDescData
}

var file_mcp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mcp_proto_goTypes = []interface{}{
	(InProcessWorkflow)(0), // 0: InProcessWorkflow
	(MCPMethod)(0),         // 1: MCPMethod
}
var file_mcp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_proto_init() }
func file_mcp_proto_init() {
	if File_mcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mcp_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_proto_goTypes,
		DependencyIndexes: file_mcp_proto_depIdxs,
		EnumInfos:         file_mcp_proto_enumTypes,
	}.Build()
	File_mcp_proto = out.File
	file_mcp_proto_rawDesc = nil
	file_mcp_proto_goTypes = nil
	file_mcp_proto_depIdxs = nil
}
